# Generated by Django 5.1.7 on 2025-03-28 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='patch',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='patches',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Image 1', max_length=100),
        ),
        migrations.AddField(
            model_name='patch',
            name='description',
            field=models.TextField(default='Initial patch description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Initial product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='patch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.patch'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(default='Patch 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product 1', max_length=100),
        ),
        migrations.AddField(
            model_name='patch',
            name='release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='product_app.release'),
        ),
    ]
