# Generated by Django 5.1.7 on 2025-03-28 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_release_remove_patch_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='release',
            name='version',
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='Default Image Name', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='http://example.com/default_image_url'),
        ),
        migrations.AddField(
            model_name='patch',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.CharField(default='Default Release Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='description',
            field=models.TextField(default='Default patch description'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(default='Default Patch Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='patch',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='product_app.release'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Default product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Default Product Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Under Testing', max_length=255)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_products', to='product_app.patch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_products', to='product_app.product')),
            ],
        ),
    ]
