# Generated by Django 5.1.7 on 2025-03-30 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_remove_image_file_remove_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='release',
            name='release_date',
        ),
        migrations.AddField(
            model_name='product',
            name='patch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.patch'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('under_testing', 'Under Testing')], default='under_testing', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='https://example.com/image1.jpg'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='description',
            field=models.TextField(default='Sample patch description'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(default='Patch1', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product1', max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(default='Sample release description'),
        ),
        migrations.AlterField(
            model_name='release',
            name='name',
            field=models.CharField(default='Release1', max_length=255),
        ),
        migrations.DeleteModel(
            name='PatchProduct',
        ),
    ]
